frequency = 2500
duration = 2000

comments = ["🔥🔥🔥", "🔥🔥🔥🔥", "🔥🔥🔥🔥🔥", "🔥❤️", "🔥❤️🔥"]

popular_hashtags = [
    "arlettemagazine",
    "arcanamagazine",
    "heavyrainmag",
    "insomniamag",
    "portraitphotography",
    "야외스냅",
    "인물촬영",
    "스냅사진촬영",
    "개인스냅",
    "good_portraits_world",
    "as_archive",
    "globe_portraits",
    "portrait_shot",
    "girlsonfilm",
    "girlportrait",
    "ourmag",
    "portraitmood",
    "777luckyfish",
    "portraituring",
    "portraitgreatness",
    "portraitvision_",
    "theportraitbazaar",
    "фотограф",
    "фотография",
    "фотосессия",
    "фото",
]

hashtags = [
    "photography",
    "photographer",
    "photooftheday",
    "portraitphotography",
    "instaphoto",
    "fotografia",
    "fotografo",
    "photojournalism",
    "photographylovers",
    "fotografía",
    "photographersofinstagram",
    "photographie",
    "photographe",
    "fotografie",
    "フォトグラフィー",
    "写真",
    "摄影",
    "摄影师",
    "фотография",
    "مصور",
    "fotografie",
    "写真好き",
    "ポートレート",
    "写真撮影",
    "摄影爱好者",
    "人像摄影",
    "风景摄影",
    "фотографиялюбителей",
    "фотомастер",
    "fotodeldia",
    "fotografiaartistica",
    "фотографиямода",
    "фотосъемка",
    "фотографияпейзаж",
    "摄影",
    "摄影师",
    "摄影",
    "摄影师",
    "تصوير",
    "صور",
]
